### PR TITLE
Updated Particle Background Animation

### LINKED ISSUE #128: Want to add Particle Background Animation
## Describe the feature

I want to add particle background animation in different pages of the website.

Some examples of how website will look after adding it to background are as :-

image

image

image

image

image

### PR DESCRIPTION
**Pull request by ROHAN842**
### Description

Particle background animation imported successfully in different pages of the website.

Fixes Issue #128

### Type of Change:

- New Feature

### CODE REVIEW

**Comment by ROHAN842** [comment]
Hey @rockingrohit9639 I have some problem in my PC that's why I couldn't push another commit in that old PR only and due to it I re-cloned the whole project and again imported all changes, also I have removed the background animation for Home page this time.
I request you to kindly merge my this PR and delete that old PR.

**Review by rockingrohit9639 — APPROVED** [review]

**Comment by ROHAN842** [comment]
@rockingrohit9639 are you merging this PR as I am not able to understand what exactly the conflict is in package-lock.json

**Comment by ROHAN842** [comment]
Also I have no idea how to write access for this repository

**Comment by kanak22** [comment]
Did u pulled the changes ? Before making a PR? ...maybe this is creating an issue

**Pull request merged**
