### PR TITLE
Bug Fix & Server finally ready for Deploy & Test

### PR DESCRIPTION
**Pull request by naveen8801**
### Description

Bug fix for navbar & Server ready for deploy.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by kanak22** [comment]
Hey @naveen8801 do you have an issue opened for this? If so then kindly link it :)

**Comment by rockingrohit9639** [comment]
> Hey @naveen8801 do you have an issue opened for this? If so then kindly link it :)

No need to open issue for it.

**Comment by naveen8801** [comment]
Hi @kanak22, this PR has no issue linked with it, it just solving some bugs imp. for server deployment & no need to include it under LGSOC.

**Comment by kanak22** [comment]
> Hi @kanak22, this PR has no issue linked with it, it just solving some bugs imp. for server deployment & no need to include it under LGSOC.

Okay 🤗

**Pull request merged**
