### PR TITLE
Update Footer.js

### LINKED ISSUE #196: Editing the footer
## Describe the bug/feature
In the footer where made with love by open source contributor is written, contributor word looks dim, I will change the word to look alike the rest of them
A clear and concise description of what the bug/feature is.

## To Reproduce

1.Change the position of Contributor word in footer
2.
3.
4.

## Logs

If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):

- OS:
- Browser:

### PR DESCRIPTION
**Pull request by NOiR-07**
### Description

Changed the  positioning of contributor word and made it to look same as othes

Fixes #ISSUE #196

### How Has This Been Tested?
Tested on my pc running localhost

### Checklist:

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials
- [X] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by satyampgt4 — CHANGES_REQUESTED** [review]
you have remove the hyperlink associated to Contributors

you only need to change color in  Footer.css

```
footer a {
    color: rgb(209, 209, 209)
}

````

**Comment by rockingrohit9639** [comment]
@NOiR-07 any update?

**Comment by NOiR-07** [comment]
> @NOiR-07 any update?

I will do it by today

**Comment by NOiR-07** [comment]
Opened the PR kindly check once

**Pull request closed without merging**
