### PR TITLE
Alignment

### LINKED ISSUE #139: Bug - Make Welcome to dashboard align perfectly with other navbar items
## Describe the bug/feature

Welcome to dashboard text after sign in or sign up , is not perfectly vertically aligned that's why giving a weird look.

Screenshot (96)_LI

## Expected behavior

All navbar items should be aligned same horizontally and vertically.

## Additional context

@rockingrohit9639 @kanak22, please add label 'good first issue' to it :))

### PR DESCRIPTION
**Pull request by RiyaGupta89**

### CODE REVIEW

**Comment by rockingrohit9639** [comment]
Hi @RiyaGupta89 I can see any code in your PR, you have only changed react-script version

**Comment by RiyaGupta89** [comment]
@rockingrohit9639 Because I've mentioned in the comment that the alignment is already correct (I've shared the ss), and if the alignment is already correct then what is the need of rewriting the styles. I've asked this in the comment that day but you asked me to make PR.

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 Because I've mentioned in the comment that the alignment is already correct (I've shared the ss), and if the alignment is already correct then what is the need of rewriting the styles. I've asked this in the comment that day but you asked me to make PR.

But, it is not aligned at my end. Ok leave it I will figure it out. Can you change the react-script version back to the previous one?

**Comment by RiyaGupta89** [comment]
@rockingrohit9639 I've changed react scripts version back to 4.0.3.

**Pull request merged**
