### PR TITLE
Added the content for Search Bar

### LINKED ISSUE #108: Separate search bar from homepage
Create a separate page and show the SearchBar there and only fetch the project when the user clicks on the search button.

### PR DESCRIPTION
**Pull request by Shaishav0507**
### Description

Hey @rockingrohit9639 
Added the content for the search bar filter.
Now you need to integrate according to your code because it is very difficult for me to integrate as I have to study the whole code which will take a lot of time.
Please check and update.
Thanks

Fixes #108 

### Type of Change:

- Bugs
- New Feature
- Documentation

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by rockingrohit9639** [comment]
> ### Description
> Hey @rockingrohit9639
> Added the content for the search bar filter.
> Now you need to integrate according to your code because it is very difficult for me to integrate as I have to study the whole code which will take a lot of time.
> Please check and update.
> Thanks
> 
> Fixes #108
> 
> ### Type of Change:
> * Bugs
> * New Feature
> * Documentation
> 
> ### How Has This Been Tested?
> ### Checklist:
> * [ ]  My PR follows the style guidelines of this project
> * [ ]  I have performed a self-review of my own code or materials
> * [ ]  I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
> * [ ]  My changes generate no new warnings
> * [ ]  New and existing unit tests pass locally with my changes

Bro, can you tell me what have you done in this PR?

**Comment by Shaishav0507** [comment]
So basically I have created a filter search according to the name.
It will display the results as you start typing any letter.

**Comment by rockingrohit9639** [comment]
> So basically I have created a filter search according to the name.
> It will display the results as you start typing any letter.

is it fixing the issue?

**Comment by Shaishav0507** [comment]
> > So basically I have created a filter search according to the name.
> > It will display the results as you start typing any letter.
> 
> is it fixing the issue?

Yes it is

**Comment by rockingrohit9639** [comment]
> > > So basically I have created a filter search according to the name.
> > > It will display the results as you start typing any letter.
> > 
> > 
> > is it fixing the issue?
> 
> Yes it is

bro, I think you did not get what was the issue. You should have ask me.

**Comment by Shaishav0507** [comment]
> > > > So basically I have created a filter search according to the name.
> > > > It will display the results as you start typing any letter.
> > > 
> > > 
> > > is it fixing the issue?
> > 
> > 
> > Yes it is
> 
> bro, I think you did not get what was the issue. You should have ask me.

Could you elaborate please?

**Comment by rockingrohit9639** [comment]
> > > > > So basically I have created a filter search according to the name.
> > > > > It will display the results as you start typing any letter.
> > > > 
> > > > 
> > > > is it fixing the issue?
> > > 
> > > 
> > > Yes it is
> > 
> > 
> > bro, I think you did not get what was the issue. You should have ask me.
> 
> Could you elaborate please?

Bro what you had to do was,
- remove search bar from the homepage
- create another page 
- add the search bar on this page

**Comment by Shaishav0507** [comment]
Ok will do it again.

**Comment by rockingrohit9639** [comment]
> Ok will do it again.

Thank you

**Pull request closed without merging**
