### PR TITLE
Points #78

### LINKED ISSUE #78: Add LGM-SOC'21 score card in readme.md
Add LGM-SOC'21 score card in readme.md

### PR DESCRIPTION
**Pull request by ishitakapoor26**
Fixes #78 

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by ishitakapoor26** [comment]
@kanak22 pls review my pr.

**Comment by kanak22** [comment]
There are 0 1 2 3 4 levels kindly add the 4th one nd correct the points of 2 and 3 :)

**Comment by ishitakapoor26** [comment]
> There are 0 1 2 3 4 levels kindly add the 4th one nd correct the points of 2 and 3 :)

okay

**Comment by kanak22** [comment]
It's good :)

**Pull request merged**
