### PR TITLE
Changed the colors of the buttons

### LINKED ISSUE #26: Different colors for different skills
Do add some different colors to different skills shown at the bottom of the project card.

### PR DESCRIPTION
**Pull request by RiyaGupta89**
I solved the issue. Please check.

### CODE REVIEW

**Comment by kanak22** [comment]
Hey @RiyaGupta89 kindly pull the changes and then push them as your PR is having some conflicts.

**Comment by RiyaGupta89** [comment]
> Hey @RiyaGupta89 kindly pull the changes and then push them as your PR is having some conflicts.

@kanak22 Please check is it okay now? I pulled the changes and pushed them back as you told me to do.

**Comment by kanak22** [comment]
Your forked repository is showing it is 60 commits behind the main project repo, click on fetch upstream and then click fetch and merge. I hope it resolves the conflicts.

**Comment by RiyaGupta89** [comment]
Please check it now, are there any conflicts?

**Comment by kanak22** [comment]
no there aren't any conflicts now :)

**Pull request merged**
