### PR TITLE
updated-preview

### PR DESCRIPTION
**Pull request by Humungus-Fungus**
### Description

Updated the preview images to match the current state of the app.

Fixes #ISSUE

### Type of Change:
- Documentation

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by kanak22** [comment]
@Humungus-Fungus this PR is for which issue?

**Comment by Humungus-Fungus** [comment]
Issue #208, “Update preview screenshots in README.md file”

**Comment by rockingrohit9639** [comment]
@Humungus-Fungus those are not updated screenshots, run it on localhost then you will find latest ss

**Comment by rockingrohit9639** [comment]
@Humungus-Fungus would you change ss or should I close this PR?

**Comment by Humungus-Fungus** [comment]
You can close it.

**Pull request closed without merging**
