### PR TITLE
Issue & PR templates added

### LINKED ISSUE #15: Create PR and Issue templates
Create Issue and PR templates for the repo.

### PR DESCRIPTION
**Pull request by naveen8801**
Solving #15 

I have added two files in the root directory of the project that are ISSUE_TEMPLATE.md & PULL_REQUEST_TEMPLATE.md

### CODE REVIEW

**Comment by rockingrohit9639** [comment]
> Solving #15
> 
> I have added two files in the root directory of the project that are ISSUE_TEMPLATE.md & PULL_REQUEST_TEMPLATE.md

@naveen8801 have you deleted package-lock.json?

**Comment by naveen8801** [comment]
> > Solving #15
> > I have added two files in the root directory of the project that are ISSUE_TEMPLATE.md & PULL_REQUEST_TEMPLATE.md
> 
> @naveen8801 have you deleted package-lock.json?

No @rockingrohit9639, I didn't delete that file, I just executed 'npm install' command.

**Comment by rockingrohit9639** [comment]
> > > Solving #15
> > > I have added two files in the root directory of the project that are ISSUE_TEMPLATE.md & PULL_REQUEST_TEMPLATE.md
> > 
> > 
> > @naveen8801 have you deleted package-lock.json?
> 
> No @rockingrohit9639, I didn't delete that file, I just executed 'npm install' command.

Have you run the project ? Was ut working?

**Comment by naveen8801** [comment]
> > > > Solving #15
> > > > I have added two files in the root directory of the project that are ISSUE_TEMPLATE.md & PULL_REQUEST_TEMPLATE.md
> > > 
> > > 
> > > @naveen8801 have you deleted package-lock.json?
> > 
> > 
> > No @rockingrohit9639, I didn't delete that file, I just executed 'npm install' command.
> 
> Have you run the project ? Was ut working?

Yaa @rockingrohit9639 , its working fine locally :))

**Comment by naveen8801** [comment]
@rockingrohit9639  should I merge the main branch once?

**Pull request merged**
