### PR TITLE
Scroll to top on every route

### LINKED ISSUE #250: 🐛  Bug : Scroll Preserve on route change
**Describe the bug**
When a user navigates from one route to the other the browser is preserving the scroll.

**To Reproduce**

Steps to reproduce the behaviour:

1. After landing into home page, scroll down a bit.
2. Click on My Courses or any other tab.
3. The scroll gets preserved.

**Expected behaviour**
On change of the route the user should be landed on the top of the page instead of the preserved scroll

**Screenshots**

### PR DESCRIPTION
**Pull request by kushal98**
### Description

I have added a ScrollToTop Component that helps user land to the top of page whenever the user navigate between routes.

Fixes #250 

### Type of Change:

- Bug Fix

### How Has This Been Tested?

I tried navigating to multiple routes and now the portal lands me on the top of the page.

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by satyampgt4 — APPROVED** [review]
LGTM !

**Comment by kushal98** [comment]
Hey @satyampgt4 

I am not sure if this is deployed as i cannot see the changes reflecting. Can you please confirm?

**Comment by satyampgt4** [comment]
it is working fine in my system. try to fetch upstream

**Comment by rockingrohit9639** [comment]
> Hey @satyampgt4
> 
> I am not sure if this is deployed as i cannot see the changes reflecting. Can you please confirm?

It is not updated with the live site. There is the different branch for production.

**Pull request merged**
