### PR TITLE
Adding footer to the website as per #17

### LINKED ISSUE #17: Footer for project zone Website
Can I get the issue?

Footer will have name and details of project admin @rockingrohit9639

### PR DESCRIPTION
**Pull request by mayankmohak**
### Description

Applied the Footer to the Website.

Fixes #17 

### Type of Change:

- New Feature

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by naveen8801** [comment]
Hi @mayankmohak, can you please add a screenshot of the footer component you have added, in PR description :))

**Comment by mayankmohak** [comment]
Hi this is what i have implemented ,  contributors has link to [link](https://github.com/rockingrohit9639/project-zone/graphs/contributors)
image

please review and assist more changes.

**Comment by naveen8801** [comment]
> Hi this is what i have implemented , contributors has link to [link](https://github.com/rockingrohit9639/project-zone/graphs/contributors)
> image
> 
> please review and assist more changes.

Looking good to me ❤️ , just make sure it remain center-aligned in mobile view also

**Comment by mayankmohak** [comment]
@naveen8801  i have tested the changes

**Pull request merged**
